INSERT INTO Suppliers (Name, ContactEmail, Address, Phone) VALUES ('Sports Goods', 'sportsgoods@supplier.com', 'Str. Wowwoo, Mexico', '0767347447');
INSERT INTO Suppliers (Name, ContactEmail, Address, Phone) VALUES ('GamesForFun', 'gamesforfun@supplier.com', 'Str. Cantemir, Iasi', '0754532535');
INSERT INTO Suppliers (Name, ContactEmail, Address, Phone) VALUES ('PlayNow', 'playnow@supplier.com', 'Str. Locococo, Austin', '0785485848');
INSERT INTO Suppliers (Name, ContactEmail, Address, Phone) VALUES ('Aerospae', 'aerospae@supplier.com', 'Str. Baguette, Paris', '0745573473');
INSERT INTO Suppliers (Name, ContactEmail, Address, Phone) VALUES ('SpeedForNeed', 'speedforneed@supplier.com', 'Str. Suberek, Turkey', '0757436366');

INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Adidasi obraznici', 'Niste adidasi foarte obraznici', 89, 100, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES('Adidasi putere', 'Marca VS, adidasi de calitate', 101, 120, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES('Tricou sala', 'Eat big get big yeaaa buddy', 244, 150, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Tricou obraznic', 'Niste obraznici 2', 200, 90, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Sapca cool', 'O sapca foarte cool pentru vara', 50, 200, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Sac de box', 'Pentru antrenamente intense', 300, 30, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Minge de fotbal', 'Pentru meciuri cu prietenii', 75, 100, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Manusi sala', 'Protejeaza-ti mainile', 40, 150, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Adidasi running', 'Perfecti pentru alergare', 150, 110, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Geanta sport', 'Ideala pentru sala de sport', 120, 80, 1);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Joc de societate', 'Distreaza-te cu prietenii', 60, 200, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Puzzle', 'Puzzle de 1000 de piese', 30, 150, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Tabla de sah', 'Pentru iubitorii de sah', 150, 100, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Joc Monopoly', 'Clasicul joc Monopoly', 70, 120, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Joc de carti', 'Divertisment pentru toata familia', 20, 250, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Rubik’s Cube', 'Provocare si distractie', 25, 300, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Darts', 'Joc de darts pentru acasa', 45, 150, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Joc Uno', 'Uno pentru seri distractive', 15, 200, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Joc video', 'Cel mai nou joc video', 250, 100, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Set de poker', 'Pentru seri de poker cu prietenii', 100, 80, 2);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Consola Gaming', 'Consola de ultima generatie', 500, 60, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Joc VR', 'Experienta virtuala imersiva', 150, 70, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Controller wireless', 'Controler ergonomic pentru gaming', 90, 100, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Casti Gaming', 'Casti cu sunet surround', 120, 80, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Tastatura mecanica', 'Tastatura rapida pentru gaming', 110, 90, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Mouse Gaming', 'Mouse precis pentru jucatori', 70, 110, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Scaun Gaming', 'Scaun confortabil pentru sesiuni lungi', 200, 50, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Webcam pentru streaming', 'Webcam HD pentru streameri', 140, 70, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Microfon', 'Microfon de inalta calitate pentru gaming', 100, 85, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Lumini RGB', 'Iluminare RGB pentru setup-ul de gaming', 60, 120, 3);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Model avion', 'Model detaliat de avion', 250, 40, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Telescop', 'Telescop pentru observatii spatiale', 300, 30, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Kit de robotica', 'Kit educativ pentru asamblarea robotilor', 220, 50, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Drone', 'Drone pentru inregistrari aeriene', 400, 25, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Racheta model', 'Racheta de modelism', 150, 45, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Microscop', 'Microscop pentru observatii detaliate', 200, 40, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Lanterna puternica', 'Lanterna pentru explorari', 80, 100, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Busola digitala', 'Busola pentru orientare precisa', 50, 150, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Harta stelara', 'Harta detaliata a constelatiilor', 70, 90, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Binoclu', 'Binoclu de mare putere', 120, 80, 4);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Bicicleta de cursa', 'Bicicleta rapida pentru competitii', 800, 20, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Casca de protectie', 'Casca pentru siguranta in timpul cursei', 100, 60, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Anvelope de cursa', 'Anvelope de inalta performanta', 120, 70, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Set de reparatii', 'Kit pentru reparatii rapide', 50, 100, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Manusi de ciclism', 'Manusi confortabile pentru ciclism', 40, 120, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Geanta de hidratare', 'Sistem de hidratare pentru curse lungi', 90, 80, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Lumini bicicleta', 'Lumini LED pentru siguranta', 30, 150, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Pedale performante', 'Pedale pentru o pedalare eficienta', 60, 90, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('Ochelari de soare', 'Ochelari pentru protectie UV', 70, 110, 5);
INSERT INTO Products (Name, Description, Price, StockQuantity, SupplierID) VALUES ('GPS pentru biciclete', 'Dispozitiv GPS pentru trasee', 200, 40, 5);

INSERT INTO Customers (FirstName, LastName, Email, Address, Phone) VALUES ('John', 'Doe', 'john@example.com', '1234 Main St', '555-1234');
INSERT INTO Customers (FirstName, LastName, Email, Address, Phone) VALUES ('Jane', 'Smith', 'jane@example.com', '5678 Main St', '555-5678');
INSERT INTO Customers (FirstName, LastName, Email, Address, Phone) VALUES ('Alice', 'Johnson', 'alice@example.com', '9101 Main St', '555-9101');
INSERT INTO Customers (FirstName, LastName, Email, Address, Phone) VALUES ('Bob', 'Brown', 'bob@example.com', '3456 Second St', '555-3456');
INSERT INTO Customers (FirstName, LastName, Email, Address, Phone) VALUES ('Carol', 'Davis', 'carol@example.com', '7890 Third St', '555-7890');

INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (1, TO_DATE('2023-01-01', 'YYYY-MM-DD'), 'Delivered');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (1, TO_DATE('2023-01-03', 'YYYY-MM-DD'), 'Shipped');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (1, TO_DATE('2023-01-05', 'YYYY-MM-DD'), 'Processing');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (2, TO_DATE('2023-01-02', 'YYYY-MM-DD'), 'Delivered');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (2, TO_DATE('2023-01-04', 'YYYY-MM-DD'), 'Shipped');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (2, TO_DATE('2023-01-06', 'YYYY-MM-DD'), 'Processing');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (3, TO_DATE('2023-01-07', 'YYYY-MM-DD'), 'Delivered');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (3, TO_DATE('2023-01-09', 'YYYY-MM-DD'), 'Shipped');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (3, TO_DATE('2023-01-11', 'YYYY-MM-DD'), 'Processing');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (4, TO_DATE('2023-01-08', 'YYYY-MM-DD'), 'Delivered');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (4, TO_DATE('2023-01-10', 'YYYY-MM-DD'), 'Shipped');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (4, TO_DATE('2023-01-12', 'YYYY-MM-DD'), 'Processing');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (5, TO_DATE('2023-01-13', 'YYYY-MM-DD'), 'Delivered');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (5, TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'Shipped');
INSERT INTO Orders (CustomerID, OrderDate, Status) VALUES (5, TO_DATE('2023-01-17', 'YYYY-MM-DD'), 'Processing');

INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (1, 1, 1, 89);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (2, 3, 1, 244);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (3, 2, 3, 101);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (4, 5, 1, 50);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (5, 4, 2, 200);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (6, 6, 1, 300);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (7, 7, 1, 75);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (8, 8, 1, 40);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (9, 9, 1, 150);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (10, 10, 2, 120);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (11, 11, 1, 60);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (12, 12, 2, 30);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (13, 13, 1, 150);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (14, 14, 1, 70);
INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES (15, 15, 2, 20);